package anchovy.sandbox.component;

import java.util.Map;

import anchovy.util.Packet;
import anchovy.util.Tag;

/**
 * This class the the representation of a Generator within the power plant. 
 * @author Harrison
 *
 */
public class Generator extends Component {
	protected Double electricityGenerated = 0.0;
	protected Double generationRatio = 1.5;
	
	/**
	 * Set up the generator, mostly done in the Component.
	 * @param name The unique name of the component. 
	 */
	public Generator(String name){
		super(name);
		this.type = "Generator";
	}
	
	@Override
	public Packet toPacket() {
		Packet p = new Packet(super.getHeader());
		
		p.put(Tag.compElectricity, electricityGenerated);
		
		return p;
	}

	@Override
	public void calculate() {
		super.outputFlowRate = calculateOutputFlowRate();
		electricityGenerated += super.outputFlowRate;
	}

	@Override
	/**
	 * The generator is the part of the power plant that generates the electricity
	 * The output flow rate of the generator is the amount of amount of electisity being generated per cycle.
	 * 
	 * The generation of electricity is proportional to the RPM of the turbine attached to it, not the ouput flow rate of the turbines..
	 * 
	 * @return amount of electricity generated in current cycle.
	 */
	protected Double calculateOutputFlowRate() {
		Double totalInputRPM = 0.0;
		
		for(Component c : receivesInputFrom) {
			if(c instanceof Turbine) {
				totalInputRPM += ((Turbine)c).RPM();
			}
		}
		
		return totalInputRPM * this.generationRatio;
	}

	@Override
	public void setup(Packet p) {
		super.setupHeader(p);
		
		for(Map.Entry<Tag, Object> entry : p.entrySet()) {
			switch(entry.getKey()) {
			case compElectricity:
				electricityGenerated = (Double) entry.getValue();
				break;
			default:
				break;
			}
		}
	}

	/**
	 * Rather than just the output flow rate, Generator also contains the total amount of
	 * electricity that has been generated by the plant.
	 * @return The total amount of electrisy generated by the plant.
	 */
	public double electricityGenerated() {
		return electricityGenerated;
	}

	public double generationRatio() {
		return generationRatio;
	}

	public void setGenerationRatio(Double generationRatio) {
		this.generationRatio = generationRatio;
	}

}
